// Generated by CoffeeScript 1.4.0
(function() {
  var GLOBAL, api_version, host;

  GLOBAL = {};

  api_version = 1;

  if (Ti.Platform.model === 'Simulator') {
    host = 'localhost:3000';
  } else {
    host = '192.168.11.5:3000';
  }

  GLOBAL.HOST = host;

  GLOBAL.API_URL = "http://" + host + "/api/v" + api_version;

  GLOBAL.APP_URL_SCHEME = "tibackyardclient://";

  GLOBAL.LAST_URL_SCHEME = null;

  if (Ti.App.Properties.hasProperty('user')) {
    GLOBAL.user = JSON.parse(Ti.App.Properties.getString('user'));
  } else {
    GLOBAL.user = {
      id: null,
      name: null,
      email: null,
      auth_token: null,
      device_token: Ti.Platform.getId()
    };
  }

  module.exports = GLOBAL;

}).call(this);
