// Generated by CoffeeScript 1.4.0
(function() {
  var createWindow;

  createWindow = function(tab) {
    var GLOBAL, Network, row, tableView, window, _onSuccess;
    Network = require('js/lib/Network');
    GLOBAL = require('js/lib/global');
    window = Titanium.UI.createWindow({
      title: 'Push Notification'
    });
    tableView = Ti.UI.createTableView({
      style: Ti.UI.iPhone.TableViewStyle.GROUPED,
      rowHeight: 44
    });
    window.add(tableView);
    row = Ti.UI.createTableViewRow({
      title: 'Push Notification'
    });
    tableView.setData([row]);
    _onSuccess = function(status, hash) {
      if (status !== 204) {
        alert('Can not send Push Notification');
      }
    };
    row.addEventListener('click', function(e) {
      var network;
      network = new Network({
        success: _onSuccess
      });
      network.request('POST', "" + GLOBAL.API_URL + "/users/test_apns", {
        auth_token: GLOBAL.user.auth_token
      });
    });
    return window;
  };

  module.exports = createWindow;

}).call(this);
