// Generated by CoffeeScript 1.4.0
(function() {
  var createWindow;

  createWindow = function(tab) {
    var GLOBAL, Network, row, table, window, _updateRowTitle;
    Network = require('js/lib/Network');
    GLOBAL = require('js/lib/global');
    window = Titanium.UI.createWindow({
      title: 'Login'
    });
    table = Ti.UI.createTableView({
      style: Ti.UI.iPhone.TableViewStyle.GROUPED,
      rowHeight: 44
    });
    window.add(table);
    row = Ti.UI.createTableViewRow({
      title: 'Login via Facebook',
      color: 'green'
    });
    table.setData([row]);
    _updateRowTitle = function() {
      if (Ti.App.Properties.getBool('is_logged_in')) {
        row.title = 'Logout';
        row.color = 'green';
      } else {
        row.title = 'Login via Facebook';
        row.color = 'red';
      }
    };
    row.addEventListener('click', function(e) {
      Ti.Platform.openURL("http://" + GLOBAL.HOST + "/auth/facebook");
    });
    window.addEventListener('focus', function(e) {
      _updateRowTitle();
    });
    return window;
  };

  module.exports = createWindow;

}).call(this);
